---@class BotNames
BotNames = {
	-- Normal Names.
	'Liam',
	'Noah',
	'Oliver',
	'William',
	'Elijah',
	'James',
	'Benjamin',
	'Lucas',
	'Mason',
	'Ethan',
	'Alexander',
	'Henry',
	'Jacob',
	'Michael',
	'Daniel',
	'Logan',
	'Jackson',
	'Sebastian',
	'Jack',
	'Aiden',
	'Owen',
	'Samuel',
	'Matthew',
	'Joseph',
	'Levi',
	'Mateo',
	'John',
	'Wyatt',
	'Carter',
	'Julian',
	'Luke',
	'Grayson',
	'Isaac',
	'Jayden',
	'Theodore',
	'Gabriel',
	'Anthony',
	'Dylan',
	'Leo',
	'Lincoln',
	'Jaxon',
	'Asher',
	'Josiah',
	'Andrew',
	'Thomas',
	'Joshua',
	'Ezra',
	'Hudson',
	'Charles',
	'Caleb',
	'Isaiah',
	'Ryan',
	'Nathan',
	'Adrian',
	'Christian',
	'Maverick',
	'Colton',
	'Elias',
	'Aaron',
	'Eli',
	'Landon',
	'Jonathan',
	'Nolan',
	'Hunter',
	'Cameron',
	'Connor',
	'Santiago',
	'Jeremiah',
	'Ezekiel',
	'Angel',
	'Roman',
	'Easton',
	'Miles',
	'Robert',
	'Jameson',
	'Nicholas',
	'Greyson',
	'Cooper',
	'Ian',
	'Carson',
	'Axel',
	'Jaxson',
	'Dominic',
	'Leonardo',
	'Luca',
	'Austin',
	'Jordan',
	'Adam',
	'Xavier',
	'Jose',
	'Jace',
	'Everett',
	'Declan',
	'Evan',
	'Kayden',
	'Parker',
	'Wesley',
	'Kai',
	'Lesley',
	'Sparrow',
	'Rudy',
	'Lars',
	'Marlon',
	'Tim',
	'Tom',
	'Bob',
	'Lianne',
	'Nelson',
	'Herald',
	'Johan',
	'Jason',
	'Sean',
	'Trevor',
	'Steve',
	'Jeff',
	'Edward',
	'Aren',
	'Zachary',
	'Pete',
	'Diana',
	'Riemmelth',
	'Craig',
	'Lew',
	'Christina',
	'George',
	'Horst',
	'Romeo',
	'Erwin',
	'Robbe',
	'Joker',
	'Rube',
	'Leon',
	'Zaviar',
	-- Devs.
	'Bizzi',
	'FlashHit',
	'Bree',
	'Arnold',
	'ThyKingdomCome',
	'Major',
	'Joe',
	'Firjen',
	'Sjoerd',
	'Kiwi',
	'NoFaTe',
	-- Contributors.
	'BOB',
	'MeisterPeitsche',
	'DuTcHrEaGaN',
	'SmartShots',
	'RekkieSA',
	'MrDonPotato',
	'KrazyIvan',
	'GaryTheNoTrashCougar',
	'Augusta',
	'Rolling Waves',
	-- Supporters.
	'jacky890818',
	'Cosmin',
	'qnr3343',
	'akebono047',
	-- Other names
	'LunyblacAseity',
	'C4EvC4Elius',
	'ivan0394',
	'tagener-noisuf',
	'Aseityja753',
	'WordplayAmelus',
	'Ameluslan93',
	'EvmonPapren',
	'Jay_legFusee',
	'Fuseered2',
	'Paprenjak270101',
	'Crayos2Ruber',
	'BevusGabion',
	'AstawNiff',
	'Niffper1289',
	'Junan6Mazut',
	'Mazutwerty89983nr2',
	'CharpleZincic',
	'Lollapalooza',
	'MrcheeksUncate',
	'Uncatemon369',
	'KnittedFuligo',
	'Fuligostervdb',
	'TriutLunacy',
	'Lunacytcb0987',
	'BagladyLablab',
	'Lablabpon97',
	'CanotMullet',
	'Mulletytedy',
	'GarnierRubigo',
	'Rubigova252',
	'KormiXyston',
	'MillstonEbb',
	'Ebbmily3452',
	'Ruborooo123',
	'FrugieNoyade',
	'Noyadetes9',
	'SchmidtdoggTabard',
	'Tabardta38x',
	'BuchnerAgnosy',
	'ExplodLar',
	'Larle1511',
	'AnnieKitsch',
	'Kitschsen56',
	'IzyadxIberis',
	'MazolCenoby',
	'Cenobyrier13',
	'ThecudBummel',
	'Bummelro_l',
	'Mr_pookPteric',
	'ProajB0lide',
	'Bolidewe789',
	'AdaiKava',
	'Kavapburnz',
	'Jossis0Lumen',
	'Lumenko125',
	'HarunLydian',
	'AcrolEclat',
	'EllaunTazza',
	'Tazzaka2003',
	'BuffyblonKylin',
	'Kylinmo773',
	'DibujFleam',
	'Fleamderb10',
	'IfonModish',
	'Modishhost7518',
	'LptvClem',
	'Clemlue7x',
	'FlexilSabin',
	'Sabinfoot12',
	'UnzaaTeen',
	'Teenman93',
	'McdoubObtest',
	'Obtestruixr',
	'Mikie9Humect',
	'Humecttout40',
	'ZaredEchard',
	'Echardle_dk',
	'KademCotta',
	'Cottatley650',
	'KilemQiviut',
	'Qiviutzzxzxc',
	'Glove_Fumage',
	'Fumagevel800',
	'Layon3Olid',
	'Olidkeks',
	'Foudroyant',
	'Stasis2Credo',
	'Credoder_166',
	'Klendusic',
	--[['LordchaosVirtu',
	'Virtuheep',
	'Sphecoid',
	'Arshan9Maven',
	'Mavenrits21',
	'W1ddDank',
	'Dank3achlp',
	'The_beasToats',
	'Toatsverbr',
	'Karis3Kurgan',
	'Kurganro_x',
	'Blaze12Trover',
	'Troverle789',
	'GixanMormal',
	'Mormalni89',
	'MpoodNorsel',
	'Norselshock21',
	'CellerEtude',
	'Etudeqon74',
	'EsgarWithy',
	'Withyveach',
	'JuliaPlew',
	'Plewko1998',
	'SexyhamZymite',
	'Zymiterae7910819',
	'BropotAlow',
	'Alowtors619',
	'ThefurLimn',
	'Limnve0880',
	'CracklejTerret',
	'Terretverzz',
	'FauxPas',
	'XminebMehari',
	'Meharimerr',
	'Tjsutan2Vacky',
	'Vackyper5369',
	'LigneouSkua',
	'Skua_los',
	'MisadToison',
	'Toisoncven',
	'GarberArdass',
	'Ardassmmer',
	'Archer7Porge',
	'Porgeton1573',
	'LegalLilt',
	'Liltbis28',
	'PuppeedTercet',
	'Tercetdomdr',
	'CrazyphatPiffle',
	'Pifflelias23',
	'PmanscoutPieta',
	'Pietamicr',
	'AdvocMensal',
	'Mensalyre0',
	'PesherDammar',
	'Dammargeryk',
	'OctantNivial',
	'Niviallen3586',
	'AmendSiege',
	'Siegebarmy99',
	'ChiyuCrista',
	'Cristatcp7988',
	'TiconTund',
	'AlfiewQuotum',
	'Quotumchak',
	'TharealSimony',
	'Simonybrad',
	'McfabistPlacet',
	'Placetcest0ry',
	'VortexxFlench',
	'Flenchboss_921',
	'FazomMaya',
	'Mayanut5205',
	'Phthartic',
	'JaphetAcracy',
	'Acracyduck13',
	'SubcomBuffe',
	'Buffeyes3041',
	'WorgerIsovol',
	'Isovolrias01',
	'Djdave4Vacky',
	'Vackyja45',
	'MesocYote',
	'Yotegor141201',
	'Pinti_1Morgue',
	'Morguelden23',
	'MintboltPi',
	'Pirom101',
	'AllygrabGuidon',
	'Guidonwarf12',
	'NanidrGayal',
	'Gayal2kill47',
	'FullbodDumose',
	'Dumoseka6658',
	'BiggunsCadge',
	'Cadgesel15',
	'SigilKosher',
	'Kosherker965',
	'PostulGeoid',
	'Geoidbe194',
	'Accoucheuse',
	'GecutMimosa',
	'Mimosaves228',
	'DinitSachet',
	'Sachetjaak',
	'FirstmatMnesic',
	'Mnesicwarf132',
	'CobayDiable',
	'Diablemad0002468',
	'LarobNoyade',
	'Noyadegox72',
	'Tang_tifSamara',
	'Samaraperz3',
	'AjtakLeech',
	'Leechreeww',
	'FerromPlenum',
	'Plenumnoahs8282',
	'ReikKinkle',
	'Kinkle3wiz0',
	'MaggiorZona',
	'Zonavert246',
	'ProemAgouti',
	'Agouticial_hd',
	'LlleonlUmbel',
	'Umbeljem99',
	'CalvaMbira',
	'Mbirabelbc123',
	'HomeoSorrel',
	'Sorreldel567',
	'Xystarch',
	'ParthenFlacon',
	'Flacongalz432',
	'Triptych',
	'SalipAlgor',
	'Algorperz911',
	'Flivver',
	'LordramIrpe',
	'RikuhKore',
	'Korekristyn',
	'CandytuftOread',
	'Oreadpkids10',
	'NumafSallet',
	'Salletmon1236',
	'PajokDolmen',
	'Dolmendeath765',
	'Platysma',
	'HistryboyFretum',
	'Fretumder2436',
	'SamhitRoup',
	'BillatAraba',
	'Arabayingd25',
	'ShipcraftHiant',
	'Hiantrain666',
	'Goku11Creant',
	'FluddcarXyston',
	'Xystondcert',
	'SextantStythe',
	'Stythelithx',
	'TitoisBifid',
	'Bifidcat27',
	'LammondEre',
	'Erelilly39',
	'OggefMuslin',
	'Muslinlaus10',
	'Diphyodont',
	'JedrekDiable',
	'Diablercs_1',
	'EcnerBarn',
	'Barnman38' ]]
}

---@class BotNames
USMarinesNames = {
	'Pvt. Jackson',
	'Cpl. Ramirez',
	'Sgt. Thompson',
	'Lt. Krigs',
	'Capt. Anderson',
	'Maj. Carter',
	'Col. Reynolds',
	'Pvt. Walker',
	'Cpl. Nguyen',
	'Sgt. Patel',
	'Lt. Bennett',
	'Capt. Fisher',
	'Maj. Brooks',
	'Col. Hayes',
	'Pvt. Green',
	'Cpl. Turner',
	'Sgt. Morgan',
	'Lt. Sanders',
	'Capt. Wells',
	'Maj. Griffin',
	'Col. Price',
	'Pvt. Mitchell',
	'Cpl. Lee',
	'Sgt. Edwards',
	'Lt. Clark',
	'Capt. Rivera',
	'Maj. Foster',
	'Col. Cooper',
	'Pvt. Lewis',
	'Cpl. King',
	'Sgt. Roberts',
	'Lt. Morales',
	'Capt. Shaw',
	'Maj. Bennett',
	'Col. Hughes',
	'Pvt. Adams',
	'Cpl. Fisher',
	'Sgt. Kelly',
	'Lt. Ramirez',
	'Capt. Hayes',
	'Maj. Black',
	'Col. Stone',
	'Pvt. Reed',
	'Cpl. Diaz',
	'Sgt. Jenkins',
	'Lt. Barnes',
	'Capt. Morgan',
	'Maj. Torres',
	'Col. Scott',
	'Pvt. Butler',
	'Cpl. Perry',
	'Sgt. Ramirez',
	'Lt. Kelly',
	'Capt. Palmer',
	'Maj. Wood',
	'Col. Cox',
	'Pvt. Price',
	'Cpl. Hayes',
	'Sgt. Foster',
	'Lt. Simmons',
	'Capt. Reed',
	'Maj. Morris',
	'Col. Gray',
	'Pvt. Nelson'
}

---@class BotNames
RUMilitaryNames = {
	'Pvt. Ivanov',
	'Cpl. Petrov',
	'Sgt. Sokolov',
	'Lt. Smirnov',
	'Capt. Orlov',
	'Maj. Vasiliev',
	'Col. Egorov',
	'Pvt. Dmitriev',
	'Cpl. Ivanova',
	'Sgt. Kuznetsov',
	'Lt. Alekseev',
	'Capt. Nikiforov',
	'Maj. Fedorov',
	'Col. Romanov',
	'Pvt. Mikhailov',
	'Cpl. Zaitsev',
	'Sgt. Fomin',
	'Lt. Stepanov',
	'Capt. Volkov',
	'Maj. Belikov',
	'Col. Dmitriev',
	'Pvt. Sergeyev',
	'Cpl. Solovyov',
	'Sgt. Voronin',
	'Lt. Vinnikov',
	'Capt. Semyonov',
	'Maj. Gromov',
	'Col. Tarasov',
	'Pvt. Vasilev',
	'Cpl. Alekhin',
	'Sgt. Yefimov',
	'Lt. Filippov',
	'Capt. Zorin',
	'Maj. Tikhonov',
	'Col. Kolesnikov',
	'Pvt. Antipov',
	'Cpl. Arkhipov',
	'Sgt. Raskolnikov',
	'Lt. Shcherbakov',
	'Capt. Ponomarev',
	'Maj. Korolev',
	'Col. Ivanovich',
	'Pvt. Sidorov',
	'Cpl. Makarov',
	'Sgt. Grigoryev',
	'Lt. Timofeyev',
	'Capt. Dubrovsky',
	'Maj. Yermakov',
	'Col. Kravtsov',
	'Pvt. Alekseeva',
	'Cpl. Baranov',
	'Sgt. Savin',
	'Lt. Morozov',
	'Capt. Sorokin',
	'Maj. Zhukov',
	'Col. Karpov',
	'Pvt. Shubin',
	'Cpl. Cherepanov',
	'Sgt. Melnikov',
	'Lt. Larkin',
	'Capt. Shishkin',
	'Maj. Golubev',
	'Col. Avdeyev',
	'Pvt. Kuzmina'
}
