VehicleData = { -- thanks to Bree_Arnold

	-- Name, Type, Parttransforms, Bullet-Speeds?
	["LAV25"] = {Name = "[LAV-25]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["LAV25_AI"] = {Name = "[LAV-25]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["LAV25_Paradrop"] = {Name = "[LAV-25]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["2S25_SPRUT-SD"] = {Name = "[SPRUT-SD]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["BMP2"] = {Name = "[BMP-2M]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["BMP2_SP007"] = {Name = "[BMP-2M]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["M1Abrams"] = {Name = "[M1 ABRAMS]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["M1Abrams_AI_SP007"] = {Name = "[M1 ABRAMS]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["M1Abrams_SP007"] = {Name = "[M1 ABRAMS]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["M1Abrams_SP_Rail"] = {Name = "[M1 ABRAMS]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["T90"] = {Name = "[T-90A]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["T90_SP007"] = {Name = "[T-90A]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["T90_T55_SP007"] = {Name = "[T-90A]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["M1128-Stryker"] = {Name = "[M1128]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},
	["VanModified"] = {Name = "[RHINO]", Type =  VehicleTypes.Tank, Parts = {11, 2, 4}},

	-- AA Vehicle?
	["AAV-7A1"] = {Name = "[AAV-7A1 AMTRAC]", Type =  VehicleTypes.AntiAir, Parts = {11, 2, 4}},
	["LAV_AD"] = {Name = "[LAV-AD]", Type =  VehicleTypes.AntiAir, Parts = {11, 2, 4}},
	["VodnikPhoenix"] = {Name = "[VODNIK AA]", Type =  VehicleTypes.AntiAir, Parts = {11, 2, 4}},

	-- light Vehicle? maybe also AA?
	["9K22_Tunguska_M"] = {Name = "[9K22 TUNGUSKA-M]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["9K22_Tunguska_M_AI"] = {Name = "[9K22 TUNGUSKA-M]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["GAZ-3937_Vodnik"] = {Name = "[GAZ-3937 VODNIK]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["HumveeArmored"] = {Name = "[M1114 HMMWV]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["Humvee"] = {Name = "[M1114 HMMWV]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["HumveeArmored_hmg"] = {Name = "[M1114 HMMWV]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["Humvee_ASRAD"] = {Name = "[HMMWV ASRAD]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["HIMARS"] = {Name = "[M142]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["BTR90"] = {Name = "[BTR-90]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["VodnikModified_V2"] = {Name = "[BARSUK]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["STAR_1466"] = {Name = "[BM-23]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},
	["AC130"] = {Name = "[GUNSHIP]", Type =  VehicleTypes.LightVehicle, Parts = {11, 2, 4}},

	-- Air vehicle
	["A10_THUNDERBOLT"] = {Name = "[A-10 THUNDERBOLT]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["A10_THUNDERBOLT_spjet"] = {Name = "[A-10 THUNDERBOLT]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["AH1Z"] = {Name = "[AH-1Z VIPER]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["AH1Z_coop"] = {Name = "[AH-1Z VIPER]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["AH6_Littlebird"] = {Name = "[AH-6J LITTLE BIRD]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["AH6_Littlebird_EQ"] = {Name = "[AH-6J LITTLE BIRD]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["F16"] = {Name = "[F/A-18E SUPER HORNET]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["F18_Wingman"] = {Name = "[F/A-18E SUPER HORNET]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Ka-60"] = {Name = "[KA-60 KASATKA]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Mi28"] = {Name = "[MI-28 HAVOC]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Su-25TM"] = {Name = "[SU-25TM FROGFOOT]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Su-35BM Flanker-E"] = {Name = "[SU-35BM FLANKER-E]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Su37"] = {Name = "[SU-37]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Venom"] = {Name = "[UH-1Y VENOM]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Venom_coop"] = {Name = "[UH-1Y VENOM]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Z-11w"] = {Name = "[Z-11W]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["Wz11_SP_Paris"] = {Name = "[Z-11W]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},
	["F35B"] = {Name = "[F-35]", Type =  VehicleTypes.AirVehicle, Parts = {11, 2, 4}},


	["CivilianCar_03_Vehicle"] = {Name = "[CIVILIAN CAR]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["CivilianCar_03_Vehicle_SPJet"] = {Name = "[CIVILIAN CAR]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["DeliveryVan_Vehicle"] = {Name = "[DELIVERY VAN]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["GrowlerITV"] = {Name = "[GROWLER ITV]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["GrowlerITV_Valley"] = {Name = "[GROWLER ITV]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["Paris_SUV"] = {Name = "[SUV]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["Paris_SUV_Coop"] = {Name = "[SUV]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["Sniper_SUV"] = {Name = "[SUV]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["PoliceVan_Vehicle"] = {Name = "[POLICE VAN]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["RHIB"] = {Name = "[RHIB BOAT]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["TechnicalTruck"] = {Name = "[TECHNICAL TRUCK]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["TechnicalTruck_Restricted"] = {Name = "[TECHNICAL TRUCK]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["VDV Buggy"] = {Name = "[VDV Buggy]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["Villa_SUV"] = {Name = "[SUV]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["QuadBike"] = {Name = "[QUAD BIKE]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["C130"] = {Name = "[GUNSHIP]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["KLR650"] = {Name = "[DIRTBIKE]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["DPV"] = {Name = "[DPV]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},
	["SkidLoader"] = {Name = "[SKID LOADER]", Type =  VehicleTypes.NoArmorVehicle, Parts = {11, 2, 4}},

	-- MAV / BOt
	["EODBot"] = {Name = "[EOD BOT]", Type =  VehicleTypes.MavBot, Parts = {11, 2, 4}},
	["MAV"] = {Name = "[MAV]", Type =  VehicleTypes.MavBot, Parts = {11, 2, 4}},
}
