VehicleData = { -- thanks to Bree_Arnold

	-- Name, Type, Parttransforms, Bullet-Speeds?
	["LAV25"] = {"[LAV-25]", VehicleTypes.Tank, {11, 2, 4}},
	["LAV25_AI"] = {"[LAV-25]", VehicleTypes.Tank, {11, 2, 4}},
	["LAV25_Paradrop"] = {"[LAV-25]", VehicleTypes.Tank, {11, 2, 4}},
	["2S25_SPRUT-SD"] = {"[SPRUT-SD]", VehicleTypes.Tank, {11, 2, 4}},
	["BMP2"] = {"[BMP-2M]", VehicleTypes.Tank, {11, 2, 4}},
	["BMP2_SP007"] = {"[BMP-2M]", VehicleTypes.Tank, {11, 2, 4}},
	["M1Abrams"] = {"[M1 ABRAMS]", VehicleTypes.Tank, {11, 2, 4}},
	["M1Abrams_AI_SP007"] = {"[M1 ABRAMS]", VehicleTypes.Tank, {11, 2, 4}},
	["M1Abrams_SP007"] = {"[M1 ABRAMS]", VehicleTypes.Tank, {11, 2, 4}},
	["M1Abrams_SP_Rail"] = {"[M1 ABRAMS]", VehicleTypes.Tank, {11, 2, 4}},
	["T90"] = {"[T-90A]", VehicleTypes.Tank, {11, 2, 4}},
	["T90_SP007"] = {"[T-90A]", VehicleTypes.Tank, {11, 2, 4}},
	["T90_T55_SP007"] = {"[T-90A]", VehicleTypes.Tank, {11, 2, 4}},
	["M1128-Stryker"] = {"[M1128]", VehicleTypes.Tank, {11, 2, 4}},
	["VanModified"] = {"[RHINO]", VehicleTypes.Tank, {11, 2, 4}},

	-- AA Vehicle?
	["AAV-7A1"] = {"[AAV-7A1 AMTRAC]", VehicleTypes.AntiAir, {11, 2, 4}},
	["LAV_AD"] = {"[LAV-AD]", VehicleTypes.AntiAir, {11, 2, 4}},
	["VodnikPhoenix"] = {"[VODNIK AA]", VehicleTypes.AntiAir, {11, 2, 4}},

	-- light Vehicle? maybe also AA?
	["9K22_Tunguska_M"] = {"[9K22 TUNGUSKA-M]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["9K22_Tunguska_M_AI"] = {"[9K22 TUNGUSKA-M]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["GAZ-3937_Vodnik"] = {"[GAZ-3937 VODNIK]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["HumveeArmored"] = {"[M1114 HMMWV]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["Humvee"] = {"[M1114 HMMWV]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["HumveeArmored_hmg"] = {"[M1114 HMMWV]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["Humvee_ASRAD"] = {"[HMMWV ASRAD]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["HIMARS"] = {"[M142]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["BTR90"] = {"[BTR-90]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["VodnikModified_V2"] = {"[BARSUK]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["STAR_1466"] = {"[BM-23]", VehicleTypes.LightVehicle, {11, 2, 4}},
	["AC130"] = {"[GUNSHIP]", VehicleTypes.LightVehicle, {11, 2, 4}},

	-- Air vehicle
	["A10_THUNDERBOLT"] = {"[A-10 THUNDERBOLT]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["A10_THUNDERBOLT_spjet"] = {"[A-10 THUNDERBOLT]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["AH1Z"] = {"[AH-1Z VIPER]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["AH1Z_coop"] = {"[AH-1Z VIPER]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["AH6_Littlebird"] = {"[AH-6J LITTLE BIRD]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["AH6_Littlebird_EQ"] = {"[AH-6J LITTLE BIRD]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["F16"] = {"[F/A-18E SUPER HORNET]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["F18_Wingman"] = {"[F/A-18E SUPER HORNET]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Ka-60"] = {"[KA-60 KASATKA]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Mi28"] = {"[MI-28 HAVOC]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Su-25TM"] = {"[SU-25TM FROGFOOT]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Su-35BM Flanker-E"] = {"[SU-35BM FLANKER-E]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Su37"] = {"[SU-37]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Venom"] = {"[UH-1Y VENOM]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Venom_coop"] = {"[UH-1Y VENOM]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Z-11w"] = {"[Z-11W]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["Wz11_SP_Paris"] = {"[Z-11W]", VehicleTypes.AirVehicle, {11, 2, 4}},
	["F35B"] = {"[F-35]", VehicleTypes.AirVehicle, {11, 2, 4}},


	["CivilianCar_03_Vehicle"] = {"[CIVILIAN CAR]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["CivilianCar_03_Vehicle_SPJet"] = {"[CIVILIAN CAR]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["DeliveryVan_Vehicle"] = {"[DELIVERY VAN]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["GrowlerITV"] = {"[GROWLER ITV]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["GrowlerITV_Valley"] = {"[GROWLER ITV]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["Paris_SUV"] = {"[SUV]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["Paris_SUV_Coop"] = {"[SUV]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["Sniper_SUV"] = {"[SUV]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["PoliceVan_Vehicle"] = {"[POLICE VAN]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["RHIB"] = {"[RHIB BOAT]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["TechnicalTruck"] = {"[TECHNICAL TRUCK]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["TechnicalTruck_Restricted"] = {"[TECHNICAL TRUCK]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["VDV Buggy"] = {"[VDV Buggy]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["Villa_SUV"] = {"[SUV]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["QuadBike"] = {"[QUAD BIKE]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["C130"] = {"[GUNSHIP]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["KLR650"] = {"[DIRTBIKE]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["DPV"] = {"[DPV]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},
	["SkidLoader"] = {"[SKID LOADER]", VehicleTypes.NoArmorVehicle, {11, 2, 4}},

	-- MAV / BOt
	["EODBot"] = {"[EOD BOT]", VehicleTypes.MavBot, {11, 2, 4}},
	["MAV"] = {"[MAV]", VehicleTypes.MavBot, {11, 2, 4}},
}
