Config = {
    maxNumberOfBots = 40,
    spawnInSameTeam = false,
    exploding = false,
    traceDelta = 0.2,
    spawnOnLevelstart = false,
    initNumberOfBots = 5,
    botKit = 4, -- 1 = assault, 2 = engineer, 3 = support, 4 = recon
    maxTraceNumber = 10

}

BotNames = {
    "BOT_Liam",
    "BOT_Noah",
    "BOT_Oliver",
    "BOT_William",
    "BOT_Elijah",
    "BOT_James",
    "BOT_Benjamin",
    "BOT_Lucas",
    "BOT_Mason",
    "BOT_Ethan",
    "BOT_Alexander",
    "BOT_Henry",
    "BOT_Jacob",
    "BOT_Michael",
    "BOT_Daniel",
    "BOT_Logan",
    "BOT_Jackson",
    "BOT_Sebastian",
    "BOT_Jack",
    "BOT_Aiden",
    "BOT_Owen",
    "BOT_Samuel",
    "BOT_Matthew",
    "BOT_Joseph",
    "BOT_Levi",
    "BOT_Mateo",
    "BOT_David",
    "BOT_John",
    "BOT_Wyatt",
    "BOT_Carter",
    "BOT_Julian",
    "BOT_Luke",
    "BOT_Grayson",
    "BOT_Isaac",
    "BOT_Jayden",
    "BOT_Theodore",
    "BOT_Gabriel",
    "BOT_Anthony",
    "BOT_Dylan",
    "BOT_Leo",
    "BOT_Lincoln",
    "BOT_Jaxon",
    "BOT_Asher",
    "BOT_Christopher",
    "BOT_Josiah",
    "BOT_Andrew",
    "BOT_Thomas",
    "BOT_Joshua",
    "BOT_Ezra",
    "BOT_Hudson",
    "BOT_Charles",
    "BOT_Caleb",
    "BOT_Isaiah",
    "BOT_Ryan",
    "BOT_Nathan",
    "BOT_Adrian",
    "BOT_Christian",
    "BOT_Maverick",
    "BOT_Colton",
    "BOT_Elias",
    "BOT_Aaron",
    "BOT_Eli",
    "BOT_Landon",
    "BOT_Jonathan",
    "BOT_Nolan",
    "BOT_Hunter",
    "BOT_Cameron",
    "BOT_Connor",
    "BOT_Santiago",
    "BOT_Jeremiah",
    "BOT_Ezekiel",
    "BOT_Angel",
    "BOT_Roman",
    "BOT_Easton",
    "BOT_Miles",
    "BOT_Robert",
    "BOT_Jameson",
    "BOT_Nicholas",
    "BOT_Greyson",
    "BOT_Cooper",
    "BOT_Ian",
    "BOT_Carson",
    "BOT_Axel",
    "BOT_Jaxson",
    "BOT_Dominic",
    "BOT_Leonardo",
    "BOT_Luca",
    "BOT_Austin",
    "BOT_Jordan",
    "BOT_Adam",
    "BOT_Xavier",
    "BOT_Jose",
    "BOT_Jace",
    "BOT_Everett",
    "BOT_Declan",
    "BOT_Evan",
    "BOT_Kayden",
    "BOT_Parker",
    "BOT_Wesley",
    "BOT_Kai"
}