"""Execute the inner functions of tools/create_settings.py to create a temporary Config.lua 
and compare it with the original Config.lua file already merged on dev branch. This test must 
be executed after any change in get_settings and get_settings_lines, by doing this we will 
ensure it is creating the same file."""

from filecmp import cmp
from pathlib import Path

from src.tools.addons.gets import get_settings, get_settings_lines, get_to_root


def test_create_settings(tmp_path: Path) -> None:
    """Test create_settings algorithm.

    Args:
        - tmp_path - built-in pytest fixture to create Pathlib temporary files

    Returns:
        None
    """
    get_to_root()
    original_config_path = "ext/Shared/Config.lua"
    d = tmp_path / "sub"
    d.mkdir()
    temp_config_path = d / "temp_file.lua"

    all_settings = get_settings(first_key="Name")
    with temp_config_path.open("a") as temp_config:
        temp_config.write(
            """-- This file is autogenerated out of the Settings/SettingsDefinition.lua file. 
-- For permanent changes, use this file and regenerate the Config.lua file. \n
---@class Config
Config = {
    """
        )
        out_file_lines = get_settings_lines(all_settings)
        for line in out_file_lines:
            temp_config.write(line + " \n")

    assert cmp(f"{d}/temp_file.lua", original_config_path)
