from loguru import logger

from tools.addons.gets import get_it_running, get_settings, get_settings_lines


def create_settings() -> None:

    config_file = "ext/Shared/Config.lua"
    all_settings = get_settings(first_key="Name")

    with open(config_file, "w", encoding="utf-8") as out_file:
        out_file.write(
            """-- This file is autogenerated out of the Settings/SettingsDefinition.lua file. 
-- For permanent changes, use this file and regenerate the Config.lua file. \n
---@class Config
Config = {
    """
        )
        out_file_lines = get_settings_lines(all_settings)
        for line in out_file_lines:
            out_file.write(line + " \n")
        logger.info("Config.lua has been built")


if __name__ == "__main__":
    get_it_running(create_settings)
