#     Copyright (C) 2021, Firjens <firjen@plontivion.com>
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as published
#     by the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

import json
import sys
from datetime import datetime

workflow_configuration_structure = "./.funbots/workflow/conf_generator/config.json"  # URL to the configuration file skeleton
workflow_configuration_file = "./ext/Shared/Config.lua"  # URL to the path to generate to

print("Generating the fun-bots configuration file...")

# Read and parse the JSON. Failure will not be tolerated and should cause the action to fail.
try:
    s_jsonFile = json.load(open(workflow_configuration_structure))
except:
    print("[ERROR] Failed to load or parse the JSON located at %s" % workflow_configuration_structure)
    sys.exit(1)

# Write the JSON to the target file in Lua
with open(workflow_configuration_file, "w") as outFile:
    outFile.write(
        "-- This file was automatically generated by the fun-bots Github on %s (UTC)! " % datetime.today().strftime('%d-%m-%Y %H:%M:%S'))

    i = 0  # We use this variable to see how many values we've looped.

    # Loop through the initial objects
    for value in s_jsonFile:
        i += 1

        # If it's empty, don't generate it.
        if not value[0]:
            print("[WARN] Refused to generate %s. Empty variables are not generated!" % value)
            continue

        # Add the value
        outFile.write(value + " = {\n")

        ii = 0
        for sub in s_jsonFile[value]:
            if sub["type"] == "category":

                # Add category description
                if sub["description"]:
                    for description in sub["description"].split('\n'):
                        outFile.write("    -- " + description + "\n")

                outFile.write("    " + sub["name"] + " = {\n")

                ii = 0
                for subber in sub["items"]:
                    ii += 1

                    # Add the comments about the item
                    if subber["description"]:
                        for description in subber["description"].split('\n'):
                            outFile.write("        -- " + description + "\n")

                    # Add the configurable option
                    # If string, append "
                    if subber["data"]["type"] == "str":
                        outFile.write("        " + subber["name"] + " = \"" + subber["data"]["default"] + "\"")
                    else:
                        outFile.write("        " + subber["name"] + " = " + subber["data"]["default"])

                    # Add variable information
                    outFile.write(", -- " + "default: " + subber["data"]["default"] + " (" + subber["data"]["type"] + ")")

                    # Add variable info
                    if subber["data"]["information"]:
                        outFile.write(" " + subber["data"]["information"])
                    outFile.write("\n")

                    # Add double space if variable below
                    if len(sub["items"]) > ii:
                        outFile.write("\n")

                outFile.write("    }\n")
                continue

            if sub["type"] == "item":
                ii += 1

                # Add the comments about the item
                if sub["description"]:
                    for description in sub["description"].split('\n'):
                        outFile.write("    -- " + description + "\n")

                # Add the configurable option
                # If string, append "
                if sub["data"]["type"] == "str":
                    outFile.write("    " + sub["name"] + " = \"" + sub["data"]["default"] + "\"")
                else:
                    outFile.write("    " + sub["name"] + " = " + sub["data"]["default"])

                # Add variable information
                outFile.write(", -- " + "default: " + sub["data"]["default"] + " (" + sub["data"]["type"] + ")")

                # Add variable info
                if sub["data"]["information"]:
                    outFile.write(" " + sub["data"]["information"])
                outFile.write("\n")

                # Add double space if variable below
                if len(s_jsonFile[value]) > ii:
                     outFile.write("\n")

                continue

            print("[WARN] Issue")
            continue

        # End the value
        outFile.write("}")

        # If there's another value after, add a space
        if len(s_jsonFile) > i:
            outFile.write("\n")

print("SUCCESS! Configuration file generated.")
